// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddPersonRequest struct {
	FirstName  string  `json:"FirstName"`
	MiddleName *string `json:"MiddleName,omitempty"`
	LastName   string  `json:"LastName"`
	Suffix     *string `json:"Suffix,omitempty"`
}

type Person struct {
	ID              string  `json:"id"`
	FirstName       string  `json:"FirstName"`
	MiddleName      *string `json:"MiddleName,omitempty"`
	LastName        string  `json:"LastName"`
	Suffix          *string `json:"Suffix,omitempty"`
	CreatedDateTime string  `json:"CreatedDateTime"`
	UpdatedDateTime *string `json:"UpdatedDateTime,omitempty"`
}
